# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/cr_kv260_base.xdc

# Block Designs: bd/cr_kv260_bd/cr_kv260_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cr_kv260_bd || ORIG_REF_NAME==cr_kv260_bd} -quiet] -quiet

# IP: bd/cr_kv260_bd/ip/cr_kv260_bd_zynq_ultra_ps_e_0_0/cr_kv260_bd_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cr_kv260_bd_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==cr_kv260_bd_zynq_ultra_ps_e_0_0} -quiet] -quiet

# XDC: c:/Users/softw/source/repos/CustomRobotics/V-AIye/KV260/CR_KV260/CR_KV260.gen/sources_1/bd/cr_kv260_bd/cr_kv260_bd_ooc.xdc
