# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/softw/source/repos/CustomRobotics/V-AIye/KV260/CR_KV260/CR_KV260.srcs/sources_1/bd/cr_kv260_bd/ip/cr_kv260_bd_zynq_ultra_ps_e_0_0/cr_kv260_bd_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'cr_kv260_bd_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/softw/source/repos/CustomRobotics/V-AIye/KV260/CR_KV260/CR_KV260.gen/sources_1/bd/cr_kv260_bd/ip/cr_kv260_bd_zynq_ultra_ps_e_0_0/cr_kv260_bd_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cr_kv260_bd_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/softw/source/repos/CustomRobotics/V-AIye/KV260/CR_KV260/CR_KV260.gen/sources_1/bd/cr_kv260_bd/ip/cr_kv260_bd_zynq_ultra_ps_e_0_0/cr_kv260_bd_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'cr_kv260_bd_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/softw/source/repos/CustomRobotics/V-AIye/KV260/CR_KV260/CR_KV260.srcs/sources_1/bd/cr_kv260_bd/ip/cr_kv260_bd_zynq_ultra_ps_e_0_0/cr_kv260_bd_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'cr_kv260_bd_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/softw/source/repos/CustomRobotics/V-AIye/KV260/CR_KV260/CR_KV260.gen/sources_1/bd/cr_kv260_bd/ip/cr_kv260_bd_zynq_ultra_ps_e_0_0/cr_kv260_bd_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cr_kv260_bd_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/softw/source/repos/CustomRobotics/V-AIye/KV260/CR_KV260/CR_KV260.gen/sources_1/bd/cr_kv260_bd/ip/cr_kv260_bd_zynq_ultra_ps_e_0_0/cr_kv260_bd_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'cr_kv260_bd_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
